version: '3.9'

services:
  yados-controller:
    container_name: yados-controller
    image: davinash/yados:1.0.0
    command: "yadosctl controller start --listen-address 192.28.0.2 --port 9090"
    volumes:
      - ./data:/data
    ports:
      - "8181:8181"
    networks:
      yados_network:
        ipv4_address: 192.28.0.2

  yados-1:
    container_name: yados-1
    image: davinash/yados:1.0.0
    command: "yadosctl server start --name yados-1 --listen-address 192.28.0.3 --wal-dir /data --port 9191 --http-port 8989 --controller 192.28.0.2:9090"
    volumes:
      - ./data:/data
    depends_on:
      - yados-controller
    ports:
      - "8989:8989"
    networks:
      yados_network:
        ipv4_address: 192.28.0.3

  yados-2:
    container_name: yados-2
    image: davinash/yados:1.0.0
    command: "yadosctl server start --name yados-2 --listen-address 192.28.0.4 --wal-dir /data --port 9192  --controller 192.28.0.2:9090"
    volumes:
      - ./data:/data
    depends_on:
      - yados-1
    networks:
      yados_network:
        ipv4_address: 192.28.0.4

  yados-3:
    container_name: yados-3
    image: davinash/yados:1.0.0
    command: "yadosctl server start --name yados-3 --listen-address 192.28.0.5 --wal-dir /data --port 9193 --controller 192.28.0.2:9090"
    volumes:
      - ./data:/data
    depends_on:
      - yados-1
      - yados-2
    networks:
      yados_network:
        ipv4_address: 192.28.0.5

networks:
  yados_network:
    ipam:
      config:
        - subnet: 192.28.0.0/16
          gateway: 192.28.0.1


