name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER_NAME : ${{secrets.DOCKER_USER_NAME}}
        DOCKER_PASSWORD : ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER_NAME -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag davinash/yados:1.0.0
    - name: Push Image to docker hub
      run: docker push ${{secrets.DOCKER_USER_NAME}}/yados
